# hey travis we need sudo for executing this build
sudo: required
services:
  - docker  #automatically install a copy of docker inside the container

before_install:
  - docker build -t xedan/docker-react -f Dockerfile.dev . #before test run we want to build our docker image
  # the tag -t is only using internally therefore not necessary to use -t xedan/docker-react

script:
  # the script assumes to be exited by default, we need to have a workaround for automatically exit
  - docker run -e CI=true xedan/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-511731229742"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY

